"""empty message

Revision ID: 214717ca035a
Revises: f35ad1f10891
Create Date: 2024-01-12 13:29:32.057408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '214717ca035a'
down_revision = 'f35ad1f10891'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'Area', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Area', type_='unique')
    # ### end Alembic commands ###
