"""empty message

Revision ID: a8735faa4c07
Revises: b05c009b0740
Create Date: 2024-01-15 10:19:43.069050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8735faa4c07'
down_revision = 'b05c009b0740'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'Artist_Availabilty', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Artist_Availabilty', type_='unique')
    # ### end Alembic commands ###
