"""empty message

Revision ID: f35ad1f10891
Revises: eff6c0f2fd88
Create Date: 2024-01-12 13:01:15.500650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f35ad1f10891'
down_revision = 'eff6c0f2fd88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Area',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('state', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_unique_constraint(None, 'Artist', ['id'])
    op.create_unique_constraint(None, 'Artist_Genre', ['id'])
    op.create_unique_constraint(None, 'Genre', ['id'])
    op.create_unique_constraint(None, 'Show', ['id'])
    op.add_column('Venue', sa.Column('area_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'Venue', ['id'])
    op.create_foreign_key(None, 'Venue', 'Area', ['area_id'], ['id'])
    op.drop_column('Venue', 'city')
    op.drop_column('Venue', 'state')
    op.create_unique_constraint(None, 'Venue_Genre', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Venue_Genre', type_='unique')
    op.add_column('Venue', sa.Column('state', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('Venue', sa.Column('city', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'Venue', type_='foreignkey')
    op.drop_constraint(None, 'Venue', type_='unique')
    op.drop_column('Venue', 'area_id')
    op.drop_constraint(None, 'Show', type_='unique')
    op.drop_constraint(None, 'Genre', type_='unique')
    op.drop_constraint(None, 'Artist_Genre', type_='unique')
    op.drop_constraint(None, 'Artist', type_='unique')
    op.drop_table('Area')
    # ### end Alembic commands ###
